message[0] = "So this was the rest of the hallway with the window.";
message[4] = "";
message[5] = "";
message[6] = "";
message[7] = "";
message[8] = "";
message[9] = "";
message_end = 0;
snd = snd_scared_hm_6;