message[0] = "My flashlight keeps flickering around the music box."
message[1] = "Somehow, I don't see any rust on it."
message[2] = "";
message[3] = "";
message[4] = "";
message[5] = "";
message[6] = "";
message[7] = "";
message[8] = "";
message[9] = "";
message_end = 1;
snd = snd_vNah;